export const PERMISSION_MAP = {
    // Navigation
    'nav-home': 1,
    'nav-stats': 1,
    'nav-accounts': 2,
    'nav-tasks': 3,
    'nav-updates': 4,
    'nav-partners': 5,
    'nav-permissions': 6,

    // Header
    'chat-bot': 7,

    // Overview
    'view-all-users': 8,

    // Services
    'tab-modules': 9,
    'tab-tasks': 10,
    'tab-finance': 11,
    'tab-equipment': 12,
    'tab-info': 13,
    'account-info': 14,
    'agent-terminal': 15,
    'task-priority-select': 16,
    'send-message': 17,
    'partner-info': 18,
    'nav-dashboard': 19,
    'nav-taskscleanup': 20,
    'nav-chats': 21,
    'tab-users': 22,
    'add-task': 23,
    'update-account': 24,
    'add-module': 25,
    'remove-module': 26,
    'add-service': 27,
    'manage-services': 28,
    'manage-finance': 29,
    'add-equipment': 30,
    'manage-equipment': 31,
    'update-info': 32,
};

export const PERMISSION_NAMES = {
    [PERMISSION_MAP['nav-home']]: 'Ümumi baxış',
    [PERMISSION_MAP['nav-accounts']]: 'Hesablar',
    [PERMISSION_MAP['nav-tasks']]: 'Tapşırıqlar',
    [PERMISSION_MAP['nav-updates']]: 'Yeniliklər',
    [PERMISSION_MAP['nav-partners']]: 'Partnyorlar',
    [PERMISSION_MAP['nav-permissions']]: 'İcazələr',
    [PERMISSION_MAP['chat-bot']]: 'Süni İntellekt (Chat)',
    [PERMISSION_MAP['view-all-users']]: 'Bütün İstifadəçiləri Gör',
    [PERMISSION_MAP['tab-modules']]: 'Modullar Tabı',
    [PERMISSION_MAP['tab-tasks']]: 'Tapşırıqlar Tabı',
    [PERMISSION_MAP['tab-finance']]: 'Maliyyə Tabı',
    [PERMISSION_MAP['tab-equipment']]: 'Avadanlıq Tabı',
    [PERMISSION_MAP['tab-info']]: 'Məlumat Tabı',
    [PERMISSION_MAP['account-info']]: 'Hesab Məlumatları',
    [PERMISSION_MAP['agent-terminal']]: 'Agent Terminalı',
    [PERMISSION_MAP['task-priority-select']]: 'Tapşırıq Prioriteti',
    [PERMISSION_MAP['send-message']]: 'Mesaj Göndər',
    [PERMISSION_MAP['partner-info']]: 'Tərəfdaş Məlumatı',
    [PERMISSION_MAP['nav-dashboard']]: 'Tapşırıq lövhəsi',
    [PERMISSION_MAP['nav-taskscleanup']]: 'Linear Təmizləmə',
    [PERMISSION_MAP['nav-chats']]: 'Dəstək Çatı',
    [PERMISSION_MAP['tab-users']]: 'İstifadəçilər Tabı',
    [PERMISSION_MAP['add-task']]: 'Tapşırıq Əlavə Et',
    [PERMISSION_MAP['update-account']]: 'Hesab Məlumatlarını Yenilə (Form)',
    [PERMISSION_MAP['add-module']]: 'Modul Əlavə Et',
    [PERMISSION_MAP['remove-module']]: 'Sil',
    [PERMISSION_MAP['add-service']]: 'Xidmət Əlavə Et',
    [PERMISSION_MAP['manage-services']]: 'Xidmət Statusunu İdarə Et',
    [PERMISSION_MAP['manage-finance']]: 'Maliyyə Əməliyyatlarını İdarə Et',
    [PERMISSION_MAP['add-equipment']]: 'Avadanlıq Əlavə Et',
    [PERMISSION_MAP['manage-equipment']]: 'Avadanlığı Redaktə et / Sil',
    [PERMISSION_MAP['update-info']]: 'Müştəri Statistikasını Redaktə Et',
};
